### PR TITLE
Fixes crash when shader is applied to main menu

### PR DESCRIPTION
**Pull request by Tyfyter**

### CODE REVIEW

**Comment by hocha113** [comment]
This is an interesting reminder. Under what circumstances would the crash mentioned in the notification be triggered? For example, would it occur if you immediately exit the game after using the ultimate technique?

**Comment by Tyfyter** [comment]
I don't know if there's a way to make this crash happen with your mod alone, I just know that it happens if someone uses a main menu theme that has a shader with your mod enabled.

**Comment by hocha113** [comment]
> I don't know if there's a way to make this crash happen with your mod alone, I just know that it happens if someone uses a main menu theme that has a shader with your mod enabled.

Oh... It seems like a mod compatibility issue? The code here really shouldn't and likely can't run in the game's main menu. Adding an extra menu check is fine. But if possible, I'd like to see the related crash log. I suspect that some operation from another mod caused this function to access a null or invalid player instance, triggering the crash when calling the CWR function.

**Comment by Tyfyter** [comment]
There is nothing stopping this code from running in a situation where it would crash in vanilla except that world generation can't be started without selecting a character first;
More than that, there isn't really anything I could change in my mod to fix this incompatibility, the best way to fix this incompatibility from your end is to add one line of code to Calamity Overhaul, the best way to fix it from my end was to make my mod add one line worth of code (via IL editing) to Calamity Overhaul.

**Comment by hocha113** [comment]
> There is nothing stopping this code from running in a situation where it would crash in vanilla except that world generation can't be started without selecting a character first; More than that, there isn't really anything I could change in my mod to fix this incompatibility, the best way to fix this incompatibility from your end is to add one line of code to Calamity Overhaul, the best way to fix it from my end was to make my mod add one line worth of code (via IL editing) to Calamity Overhaul.

Terraria Origins Mod? I'll take a look. If there is a conflict between the current online version 0.5.0.2.2 and Terraria Origins, I will release a hotfix later.

**Comment by Tyfyter** [comment]
I already released a hotfix with the aforementioned IL edit, I just made this pull request so Calamity Overhaul doesn't have any incompatibility with other mods for the same reason.
The exact nature of the issue was that using Terraria Origins' "Defiled Wastelands" menu theme with Calamity Overhaul enabled would crash the game because the former enables the filter of the associated biome.

**Comment by hocha113** [comment]
> I already released a hotfix with the aforementioned IL edit, I just made this pull request so Calamity Overhaul doesn't have any incompatibility with other mods for the same reason. The exact nature of the issue was that using Terraria Origins' "Defiled Wastelands" menu theme with Calamity Overhaul enabled would crash the game because the former enables the filter of the associated biome.

Yes, I just noticed through the debug logs that the IL hook has already been mounted. I will still proceed with the original plan to release the update to version 0.6 at the end of the month, and you can remove the IL modification at that time.

**Comment by hocha113** [comment]
IL modifications can be removed, as this type of error should no longer occur after version 0.6.

**Pull request merged**
